name: terraform apply

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
    pattern-match:
      runs-on: ubuntu-22.04
      if: |
            github.event.issue.pull_request && 
            github.event.comment.body == '/terraform apply' &&
            (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR')
      outputs:
        pr_number: ${{ steps.get-pr-number.outputs.pr_number }}
      steps:
        - name: get pr number
          id: get-pr-number
          run: |
            PR_URL="${{ github.event.issue.pull_request.url }}"
            echo Pull request number: ${PR_URL##*/}
            echo "pr_number=${PR_URL##*/}" >> "$GITHUB_OUTPUT"
    aws-deploy:
        needs: pattern-match
        strategy:
          matrix:
            terraform_environment: [kubernetes-the-hard-way-aws]
        uses: KevinGao99/kubernetes-projects-Kev/.github/workflows/terraform-action.yaml@main
        with:
          deploy: true
          terraform_environment: ${{ matrix.terraform_environment }}
          pr_number: ${{ fromJson(needs.pattern-match.outputs.pr_number) }}
          checkout_ref: ${{ format('refs/pull/{0}/merge', needs.pattern-match.outputs.pr_number) }}
        secrets:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
